import React from "react";

import Section from "../shared/Section";

import Blog1 from "../../images/blogs/blog-thumb-1.jpg";
import Blog2 from "../../images/blogs/blog-thumb-2.jpg";
import Blog3 from "../../images/blogs/blog-thumb-3.jpg";

import "./style.scss";
import Blogcard from "./blog-card";

const Blogs = () => {
    return (
        <Section
            id="blogs"
            title="Blogs & Articles"
            background="dark"
        >
            <div className="blog-content-wrapper">
                <Blogcard
                    user="Muhammad Aashan"
                    date="11-01-2018"
                    image={Blog1}
                    title="How to Grow Your Business with the help"
                    description="Hire the right people. ...
                                    Focus on established revenue sources. ...
                                    Reduce your risks. ...
                                    Be adaptable. ...
                                    Focus on the customer experience. ...
                                    Invest in yourself. ...
                                    Always think ahead. ...
                                    Boost your customer service."
                />
                <Blogcard
                    user="Muhammad Aashan"
                    date="11-01-2018"
                    image={Blog2}
                    title="How to Grow Your Business with the help"
                    description="Hire the right people. ...
                                    Focus on established revenue sources. ...
                                    Reduce your risks. ...
                                    Be adaptable. ...
                                    Focus on the customer experience. ...
                                    Invest in yourself. ...
                                    Always think ahead. ...
                                    Boost your customer service."
                />
                <Blogcard
                    user="Muhammad Aashan"
                    date="11-01-2018"
                    image={Blog3}
                    title="How to Grow Your Business with the help"
                    description="Hire the right people. ...
                                    Focus on established revenue sources. ...
                                    Reduce your risks. ...
                                    Be adaptable. ...
                                    Focus on the customer experience. ...
                                    Invest in yourself. ...
                                    Always think ahead. ...
                                    Boost your customer service."
                />
            </div>
        </Section>
    );
};

export default Blogs;
